# Generated by Django 6.0.6 on 2026-06-09 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tradingaccount_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, verbose_name='Инструмент')),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Цена входа')),
                ('exit_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Цена выхода')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Объем')),
                ('pnl', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='PnL')),
                ('commission', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Комиссия')),
                ('closed_at', models.DateTimeField(verbose_name='Дата закрытия')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='accounts.tradingaccount')),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
    ]
