# Generated by Django 6.0.6 on 2026-06-09 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='closed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата закрытия'),
        ),
    ]
