# Generated by Django 6.0.6 on 2026-06-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_trade_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='PnL'),
        ),
    ]
